// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MyIPRepository is an autogenerated mock type for the MyIPRepository type
type MyIPRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *MyIPRepository) Get(ctx context.Context) string {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMyIPRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMyIPRepository creates a new instance of MyIPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMyIPRepository(t mockConstructorTestingTNewMyIPRepository) *MyIPRepository {
	mock := &MyIPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
